name: Gov Contract CI - Deploy

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose
        run: STAKE_TOKEN="urxpx" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'RAMPAGEXP/cw-monolith-prop'
          ref: 'v0.0.1-alpha'
      - name: Test gov deploy
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh rxp16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

