name: Contract CI

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose
        run: STAKE_TOKEN="urxpx" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'RAMPAGEXP/rxpnamer'
          ref: 'v0.1.0-alpha'
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

